# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tuesday
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Based on series for https://blog.crashspace.org/. Make your own control
  panel by forking https://github.com/carlynorama/tuesday.
baseurl: "/tuesday/" # the subpath of your site, e.g. /blog
url: "http://carlynorama.github.io/tuesday" # the base hostname & protocol for your site
#twitter_username:
github_username: carlynorama
repo_name: tuesday
# Build settings
markdown: kramdown

collections:
  start:
    output: true
    title: Start Here
  sweep:
    output: true
    title: Sweep
  learn:
    output: true
    title: Learn
  engage:
    output: true
    title: Engage
  relax:
    output: true
    title: Relax
